### ISSUE TITLE
Unable to download server list. Try again later

### ISSUE THREAD

**Issue by falconws** [ansemjo/speedtest-plotter#12]
I have problem.
It doesn't work.

My setup is..

docker-compose.yml
```
version: '3'
services:
  speedtest:
    image: ansemjo/speedtest
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    restart: always
    environment:
      TZ: Asia/Tokyo

      # default is 15
      MINUTES: 60
```

Execute `docker-compose up -d`.
Then few hours later, `docker-compose logs -f` output is ..

```
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
speedtest_1  | 
speedtest_1  | Unable to download server list. Try again later
```

How to fix this problem?
